### PR TITLE
About #773

### PR DESCRIPTION
**Pull request by ebocher**
Now duplicate coordinates (first and last) are removed in case of Linestring, MultiLinestring and MultiPoint

@gpetit

### CODE REVIEW

**Comment by ebocher** [comment]
Wait before merging

**Comment by ebocher** [comment]
I don't know how to solve this issue
What about if 

Case 1 
input data = MULTIPOINT((4 4), (1 1), (1 0), (0 3), (4 4))

result = MULTIPOINT((4 4), (1 1), (1 0), (0 3))


Case 2 
input data = MULTIPOINT((4 4), (1 1), (4 4), (1 0), (0 3), (4 4))

result = MULTIPOINT((4 4), (1 1), (1 0), (0 3)) ?


Case 3
input data = LINESTRING(4 4, 1 1, 1 0, 0 3, 4 4)

result =LINESTRING(4 4, 1 1, 1 0, 0 3) ?


Case 4
input data = LINESTRING(4 4, 1 1, 4 4, 1 0, 0 3, 4 4)

result =LINESTRING(4 4, 1 1, 4 4, 1 0, 0 3) ?
or 
result =LINESTRING(4 4, 1 1,  1 0, 0 3) ?


Do we need to remove only the repeated points or also identical points ?

My proposal  is

- do not remove repeated points on a point or a multipoint geometry,
- take into account the path of the coordinates to remove the points (from start to end),
- remove  the end coordinate if it's equal to the first coordinate only in the case of linestring.

**Comment by gpetit** [comment]
Here is my point of view:
- Case 1 : ok with the example (so not agree with your proposal), we just have to explain this is particular case. If you don't want this behaviour, we should (1) create a new specific function that allows to remove duplicated points and (2) explain that ST_RemoveRepeatedPoints only works with 1 or 2 dimensions
- Case 2 : ok
- Case 3 : ok (if the linestring is closed, the last point is removed)
- Case 4 : I vote for ```result = LINESTRING(4 4, 1 1, 4 4, 1 0, 0 3)``` points are repeated only if they follow themselves

**Comment by ebocher** [comment]
I'm not agree with you on Multipoint because it's not a path of coordinates but a set of individual geometries represented in a collection.
I think that the postgis algorithm is bad

**Comment by gpetit** [comment]
Ok so in this case we restict ST_RemoveRepeatedPoints to (multi)linestring and (mutli)polygon. But how do you manage GeometryCollection ?

**Comment by ebocher** [comment]
If we have a GeometryCollection we process only linestring, polygon and we return the input geom when the geometry is a point or a multipoint.

**Comment by gpetit** [comment]
ok. So we will have to create a new functions dedicated to points (ST_RemoveDuplicatedPoints ?)

**Comment by ebocher** [comment]
ok I will change this PR

**Comment by ebocher** [comment]
Ready for a review

**Comment by ebocher** [comment]
Ping

**Comment by gpetit** [comment]
@nicolas-f this one is for you ;-)

**Comment by nicolas-f** [comment]
I can't, I digest.

**Pull request merged**
