### PR TITLE
Fix subquery

### PR DESCRIPTION
**Pull request by ebocher**
about #840

Fix subquery for SHPWrite
Test select from for ST_EXPLODE

### CODE REVIEW

**Comment by ebocher** [comment]
ping

**Comment by ebocher** [comment]
I'm only testing the select from.
To match the "parentheses " rule, the explode function must be adapted.

**Comment by ebocher** [comment]
ping

**Comment by ebocher** [comment]
pong

**Comment by nicolas-f** [comment]
Sorry missed it

**Comment by nicolas-f** [comment]
Maybe at least change minor version because the usage of methods change ?

**Pull request merged**
