### PR TITLE
St_drape function

### PR DESCRIPTION
**Pull request by ebocher**
The ST_DRAPE function permits to drape a geometry to a set of triangles.

Input geometry to drape : POINT, MULTIPOINT, LINESTRING and POLYGON
Input geometry to compute the planes :  only triangles

Notes : 
In case of linestring or polygon, the input geometry is intersected with the triangles to perform a full draping.
If a point lies on two triangles the z value of the first triangle is kept.

### CODE REVIEW

**Comment by gpetit** [comment]
Great. Why multipoint and not multiline and multipolygon ?
We also have to specify (in the doc) that triangles have to have z values (I know it's obvious)

**Comment by ebocher** [comment]
Great. Why multipoint and not multiline and multipolygon ?

Ok I will try

**Comment by gpetit** [comment]
I was only asking if there was a reason. But if you want to try you're welcome ;-)

**Comment by ebocher** [comment]
There is only one reason.. performance.
Because the current code is not very efficient. If we take into account multi geometry you could have a very large domain depending on the distance between each part of the multi.

**Comment by gpetit** [comment]
ok

**Comment by ebocher** [comment]
Use case :

```sql

DROP TABLE IF EXISTS elevation, tin;
CALL SHPREAD('/tmp/COURBEDENIVEAU.shp', 'elevation');
CREATE TABLE tin as select * from st_explode('(SELECT ST_DELAUNAY(ST_ACCUM(ST_UpdateZ(THE_GEOM,Z ))) as the_geom from elevation)');
CREATE SPATIAL INDEX ON TIN(THE_GEOM);
CALL SHPREAD('/tmp/landcover2000.shp', 'parcelles');       
CREATE SPATIAL INDEX ON PARCELLES(THE_GEOM);
CREATE TABLE parcelles_draped as select st_drape(b.the_geom, st_accum(a.the_geom)) as the_geom, b.gid from tin as a , parcelles as b where  a.the_geom && b.the_geom and st_intersects(a.the_geom, b.the_geom) group by b.the_geom;
CALL SHPWRITE('/tmp/parcelles.shp', 'PARCELLES_DRAPED');  

```

**Comment by ebocher** [comment]
This function will be improved in the future but right now : 

COURBEDENIVEAU :  42 000 linestrings
landcover2000 :  1300 polygon (40 000 points)
TIN : 35 000 triangles
parcelles : 1300 polygon (40 000 points)

Time : 8 s on my laptop (EliteBook Core I7)

**Comment by ebocher** [comment]
Ready to merge

**Pull request merged**
