### PR TITLE
Fix - allow multiple SRID table constrains

### PR DESCRIPTION
**Pull request by bedla**
Hi, I found that we are unable to call SHPRead with .prj file because of invalid constrain creation. Maybe I am missing some design consideration, but I have created PR to fix this. If you like it, just merge it :)
Thx, Ivos

### CODE REVIEW

**Comment by nicolas-f** [comment]
Is it mandatory to put a constraint name ? If not, I propose to not set one.

**Comment by bedla** [comment]
No it is not. I will update Alter SQL and update PR soon.
Ivos

**Comment by nicolas-f** [comment]
Thanks for your help. But there is a lot of small unrelated changes (replaced files, carriage returns etc). Please, can you make another pull request (from orbigisgis/master) without all theses modifications ?

Thanks

**Comment by bedla** [comment]
I will, sorry for that...

**Comment by ebocher** [comment]
Thanks a lot for your contribution. In order to integrate it please follow the instruction on the wiki page, section "Contributing".

**Comment by bedla** [comment]
I have force-pushed my original PR/branch and wrote into mailling list as suggeted. Take a look at it please. 
Thx
Ivos

**Comment by nicolas-f** [comment]
Thanks for the patch :+1:

**Pull request merged**
