### PR TITLE
Unable to transfer DB created on Win to Unix machine

### PR DESCRIPTION
**Pull request by bedla**
Hi,
I have prepared DB on Win machine and then tried to transfer it to Unix hosting machine. I found that SQL in SYS.TABLES translates directory separators to platfrom specific values even when I provide slash. It shows error in log showing that file was not found and that table will be empty (org.h2gis.drivers.file_table.FileEngine#createTable).
I think that file path should be calculated when needed and not eagerly. With patch I have fixed two failing test. First is about not closing outputstream and second is about order of columns.
Take a look, and if you will like it, you could accept it.
Thx
Ivos

### CODE REVIEW

**Comment by ebocher** [comment]
Dear @bedla ,

Thanks a lot and welcome to the H2GIS community. We will look on it asap.
Could you please also read the Contributing section at https://github.com/orbisgis/h2gis.

**Comment by bedla** [comment]
I have "signed" CLA at http://h2gis.1099522.n5.nabble.com/PR-Unable-to-transfer-DB-created-on-Win-to-Unix-machine-556-td12.html 
Ivos

**Comment by ebocher** [comment]
Thanks a lot and welcome in H2GIS community.
Please  merge @nicolas-f  PR https://github.com/bedla/h2gis/pull/1 to allow this build.

**Comment by bedla** [comment]
Done

**Comment by ebocher** [comment]
Perfect

**Comment by ebocher** [comment]
Added on https://github.com/orbisgis/h2gis/blob/master/README.md

**Pull request merged**
