### PR TITLE
JDBCUtilities isLinkedTable

### PR DESCRIPTION
**Pull request by SPalominos**
Adds a methods to JDBCUtilities to check if a table is linked.

### CODE REVIEW

**Comment by nicolas-f** [comment]
Agree, but a unit test would be welcomed.

**Comment by SPalominos** [comment]
I don't know how to create a linked table inside a test, any idea @nicolas-f ?

**Comment by ebocher** [comment]
You can create two H2 database and link one database with the other

**Comment by SPalominos** [comment]
ok

**Comment by ebocher** [comment]
+1

**Pull request merged**
