### PR TITLE
Module names

### PR DESCRIPTION
**Pull request by ebocher**
According #740, H2GIS modules have been reorganized. 

- rename the h2gis artifact id to h2gis-parent,
- rename h2gis-functions artifact id to h2gis and h2gis-functions-osgi to h2gis-osgi
- remove h2gis-ext and h2gis-ext-osgi
- update  the readme 
- remove  h2gis-network. It must be in a separate repository.

### CODE REVIEW

**Comment by nicolas-f** [comment]
Wut, we never talked about removing h2 network from h2gis.

 I do not agree to remove h2-network and all its history from this repository.  This component is widely used and is an important part of h2gis.

**Comment by nicolas-f** [comment]
So I agree up to 4573a92, with an upgrade of minor version of H2GIS.

**Comment by ebocher** [comment]
Ok I will roll-back for H2GIS-Network. 
My fault

**Comment by nicolas-f** [comment]
More easily you can checkout 4573a92  and create a new pull request

**Comment by ebocher** [comment]
Update to 1.4-SNAPSHOT

**Comment by ebocher** [comment]
Wait before merging

**Comment by ebocher** [comment]
@SPalominos 
Could you please have a look on this PR ?
I'm a bit busy

**Comment by SPalominos** [comment]
OK, I on it.

**Comment by ebocher** [comment]
Thanks a lot

**Comment by SPalominos** [comment]
@nicolas-f Can you re-review the PR ?

**Comment by nicolas-f** [comment]
Have you tried the integration with OrbisGIS ? (with a safe mode)

**Comment by ebocher** [comment]
nop

**Comment by SPalominos** [comment]
Tested with OrbisGIS and OrbisWps, PR on those repo are comming.

**Pull request merged**
