### PR TITLE
Update to last H2 to fix the issues : 

### PR DESCRIPTION
**Pull request by ebocher**
https://github.com/orbisgis/h2gis/issues/1233 and https://github.com/orbisgis/h2gis/issues/1243

See PR : 
https://github.com/h2database/h2database/pull/3364
and
https://github.com/h2database/h2database/pull/3367

Added ST_MemSize ->  https://github.com/orbisgis/h2gis/issues/1247

### CODE REVIEW

**Comment by pierromond** [comment]
Hi @ebocher,

Thank you ! Does it mean that now we should not have memory limitation ?

**Comment by ebocher** [comment]
The geometry memory limit is Integer.MAX_VALUE -> 2147483647 bytes

**Comment by pierromond** [comment]
I can't figure out if it's high or low for our applications... :)

**Comment by ebocher** [comment]
I think it's enough.  Note that the maximum size of a field in PostgreSQL is 1 GB.

**Pull request merged**
