### PR TITLE
Improve SHPWrite function to support select query as argument

### PR DESCRIPTION
**Pull request by ebocher**
eg. CALL SHPWRITE('/tmp/myfile.shp', 'select the_geom, gid from tableGeom limit 12')

### CODE REVIEW

**Comment by nicolas-f** [comment]
Sorry I remember, h2 use the parentheses to specify a sub query (like standard query in the from close and in the TableLink)

So we should have something like that

```sql
CALL SHPWRITE('/tmp/myfile.shp', '(select the_geom, gid from tableGeom limit 12)')
```

Then just check if the second parameter start and ends with "(" ")"

**Comment by ebocher** [comment]
Don't understand. Do you want to force parentheses in select query ?

**Comment by nicolas-f** [comment]
Yes like in h2:

http://www.h2database.com/html/grammar.html#create_linked_table

```If a query is used instead of the original table name, the table is read only. Queries must be enclosed in parenthesis: (SELECT * FROM ORDERS).```

**Comment by ebocher** [comment]
oupps we must also fix the ST_Explode function .

**Pull request merged**
