### PR TITLE
Update H2 version 1.4.192 -> 1.4.193

### PR DESCRIPTION
**Pull request by SPalominos**
Update H2 version 1.4.192 -> 1.4.193 (issue #717)

### CODE REVIEW

**Comment by ebocher** [comment]
You must update all pom (also in sub module)

**Comment by ebocher** [comment]
We must also fix a new dev cycle ?

**Comment by SPalominos** [comment]
For the poms, it's ok, the version of H2 is defined in the root pom as a property and then used by sub module like that :
```xml
    <dependency>
      <groupId>${h2-package}</groupId>
      <artifactId>h2</artifactId>
      <version>${h2-version}</version>
    </dependency>
```

For the cycle dev, for me, the best is to keep it into snapshot an to do a release in the same time of OrbisGIS to have both project synchronized.

**Comment by ebocher** [comment]
In H2GIS  functions module

you have 

<parent>
    <groupId>org.orbisgis</groupId>
    <artifactId>h2gis</artifactId>
    <version>1.3.1-SNAPSHOT</version>
    <relativePath>../</relativePath>
</parent>

**Comment by ebocher** [comment]
Sorry bad copy paste.
We must update the parent version

**Pull request merged**
