### PR TITLE
geojson driver improvements

### PR DESCRIPTION
**Pull request by ebocher**
This PR improves the geojson driver in order to : 

- write and read null geometries,
- support bigint,
- quote field names ,
- support variable field properties (eg a feature with 3 properties and another with only 2). 

about #675

### CODE REVIEW

**Comment by ebocher** [comment]
@nicolas-f Please have a look.

**Comment by nicolas-f** [comment]
It seems ok. But I don't know if there is a performance impact on calling TableLocation.quoteIdentifier for each value in json. At the beginning I was thinking that cachedColumnNames are used to cache the return value of TableLocation.quoteIdentifier.

If the performance is still good for a few megabytes json, it is ok as it is now.

**Comment by ebocher** [comment]
Ok. Give me 5 minutes. I will test the performance.

**Comment by ebocher** [comment]
Some basic performances : 

 Geojson file 200 mo (393 000 polygons)

Before this PR, import -> 11 s
After this PR, IMPORT -> 15 s
QGIS (2.14.1), import -> 21 s

**Comment by ebocher** [comment]
Please wait before merge

**Comment by ebocher** [comment]
ready

**Pull request merged**
